version: '3.8'

services:
  app:
    build: .
    ports:
      - "8732:8732"
    environment:
      - NODE_ENV=development
      - PORT=8732
      - MONGODB_URI=mongodb://mongodb:27017/multimodal-ai-agent
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    volumes:
      - ./client:/app/client
      - ./controllers:/app/controllers
      - ./models:/app/models
      - ./routes:/app/routes
      - ./server.js:/app/server.js
      - ./.env:/app/.env
    restart: unless-stopped

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=multimodal-ai-agent
    restart: unless-stopped

volumes:
  mongodb_data:
